name: Trigger auto deployment for ms

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ms-AutoDeployTrigger-4723bcaf-a0a4-43c2-b691-ab2efcf0afa0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrhackathonproject.azurecr.io
          registryUsername: ${{ secrets.MS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MS_REGISTRY_PASSWORD }}
          containerAppName: ms
          resourceGroup: azure-hackathon-rg
          imageToBuild: acrhackathonproject.azurecr.io/ms:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


